let
    Source = #date(2018, 1, 1),
    Dates = List.Dates(Source, 
        Duration.TotalDays(Date.AddYears(Source, 6) - Source),
        #duration(1, 0, 0, 0)),
    #"Converted to Table" = Table.FromList(Dates, 
        Splitter.SplitByNothing(), 
        type table [Date = date]),
    #"Inserted Year" = Table.AddColumn(#"Converted to Table", 
        "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", 
        "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", 
        "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Month", 
        "Week of Year", each Date.WeekOfYear([Date]), Int64.Type)
in
    #"Inserted Week of Year"
